INSERT INTO TMP_ECOM_FORECAST
SELECT
    F.ECOM_SHOP_ID,
    F.DATE_ID,
    F.HOUR_ID,
    F.ECOM_GROSS_DEMAND_FORECAST,
    F.GROSS_DEMAND_FORECAST_COMB,
    F.CREATED_AT,
    F.MODIFIED_AT,
    F.SOURCE_CURRENCY_ID,
    F.ECOM_GROSS_DEMAND_FORECAST_ORIGIN,
    F.FORECAST_ADJ,
    F.GROSS_AMNT,
    CONVERT_TZ(CAST(CURRENT_TIMESTAMP AS TIMESTAMP), 'CET', 'Europe/Moscow') AS ROW_VERSION
FROM F_ECOM_FORECAST F
WHERE F.DATE_ID = CAST(CONVERT_TZ(CURRENT_DATE,'CET','Europe/Moscow') AS DATE)
;