MERGE INTO LU_BIZAGI_CONTRACT_TYPE D
USING (
	SELECT	DISTINCT
		 BIZAGI_CONTRACT_TYPE_NAME_INT
	FROM STG_LU_BIZAGI_CASE
	WHERE BIZAGI_CONTRACT_TYPE_NAME_INT IS NOT NULL
) S ON S.BIZAGI_CONTRACT_TYPE_NAME_INT = D.BIZAGI_CONTRACT_TYPE_NAME_INT
WHEN NOT MATCHED THEN INSERT (BIZAGI_CONTRACT_TYPE_NAME_INT) VALUES (S.BIZAGI_CONTRACT_TYPE_NAME_INT)
;

MERGE INTO LU_BIZAGI_PURCHASE_TYPE D
USING (
	SELECT DISTINCT
		BIZAGI_PURCHASE_TYPE_NAME_INT
	FROM STG_LU_BIZAGI_CASE
) S ON D.BIZAGI_PURCHASE_TYPE_NAME_INT = S.BIZAGI_PURCHASE_TYPE_NAME_INT
WHEN NOT MATCHED THEN INSERT (BIZAGI_PURCHASE_TYPE_NAME_INT) VALUES (S.BIZAGI_PURCHASE_TYPE_NAME_INT)
;

-- SEPARATE MARKETING DEPARTMENT BY BRANDS
MERGE INTO STG_LU_BIZAGI_CASE DST
USING (
    WITH REE AS (
        SELECT DISTINCT
            S.BIZAGI_CASE_NO,
            S.BIZAGI_CASE_INITIATOR_ID,
            E.EMPLOYEE_NAME_INT
        FROM STG_LU_BIZAGI_CASE S
        FULL JOIN LU_EMPLOYEE E ON (
            CASE WHEN S.BIZAGI_CASE_INITIATOR_ID IS NOT NULL
                    THEN CONCAT('00', S.BIZAGI_CASE_INITIATOR_ID) = E.SAP_HR_NO
                ELSE CASE WHEN S.BIZAGI_CASE_INITIATOR_LOGIN IS NOT NULL
                    THEN LEFT(UPPER(S.BIZAGI_CASE_INITIATOR_LOGIN), 8) = LEFT(UPPER(E.EMPLOYEE_LOGIN), 8)
                END
            END
        )
        JOIN LU_PNL_COST_CENTER C ON C.PNL_COST_CENTER_ID = E.PNL_COST_CENTER_ID
        WHERE (
            CASE WHEN BIZAGI_CASE_INITIATOR_ID IS NOT NULL THEN
                CONCAT('00', BIZAGI_CASE_INITIATOR_ID) IN (
                    SELECT DISTINCT E.SAP_HR_NO
                    FROM LU_EMPLOYEE E
                             JOIN LU_PNL_COST_CENTER C
                                  ON C.PNL_COST_CENTER_ID = E.PNL_COST_CENTER_ID
                    WHERE C.PNL_COST_CENTER_CODE IN (
                        SELECT DISTINCT COST_CENTER_FOR_MARKETING
                        FROM MAN_STG_BIZAGI_DEPARTMENT
                        WHERE BIZAGI_DEPARTMENT_NAME_INT = 'Marketing Reebok'
                    )
                )
            ELSE CASE WHEN E.EMPLOYEE_LOGIN IS NOT NULL THEN
                LEFT(UPPER(E.EMPLOYEE_LOGIN), 8) IN (
                    SELECT DISTINCT LEFT(UPPER(E.EMPLOYEE_LOGIN), 8)
                    FROM LU_EMPLOYEE E
                             JOIN LU_PNL_COST_CENTER C
                                  ON C.PNL_COST_CENTER_ID = E.PNL_COST_CENTER_ID
                    WHERE C.PNL_COST_CENTER_CODE IN (
                        SELECT DISTINCT COST_CENTER_FOR_MARKETING
                        FROM MAN_STG_BIZAGI_DEPARTMENT
                        WHERE BIZAGI_DEPARTMENT_NAME_INT = 'Marketing Reebok'
                    )
                )
            END END
        )
    )
    SELECT DISTINCT
        S.BIZAGI_CASE_NO,
        S.BIZAGI_CASE_INITIATOR_ID,
        CASE WHEN REE.EMPLOYEE_NAME_INT IS NOT NULL AND REE.BIZAGI_CASE_NO IS NOT NULL THEN 'Marketing Reebok' ELSE 'Marketing Adidas' END AS BIZAGI_DEPARTMENT_NAME_INT
    FROM STG_LU_BIZAGI_CASE S
    LEFT JOIN REE ON S.BIZAGI_CASE_NO = REE.BIZAGI_CASE_NO
    WHERE S.BIZAGI_DEPARTMENT_NAME_INT = 'Marketing'
) SRC ON DST.BIZAGI_CASE_NO = SRC.BIZAGI_CASE_NO
WHEN MATCHED THEN UPDATE SET
    DST.BIZAGI_DEPARTMENT_NAME_INT = SRC.BIZAGI_DEPARTMENT_NAME_INT
;


MERGE INTO LU_BIZAGI_CASE D
USING (
	SELECT DISTINCT
		S.BIZAGI_CASE_NO,
	    E.EMPLOYEE_ID AS BIZAGI_CASE_INITIATOR_ID,
	    UPPER(SUBSTRING(S.BIZAGI_CASE_INITIATOR_LOGIN, 1, 8)) AS BIZAGI_CASE_INITIATOR_LOGIN,
	    CASE WHEN E.EMPLOYEE_NAME_INT IS NOT NULL THEN E.EMPLOYEE_NAME_INT ELSE REPLACE(S.BIZAGI_CASE_INITIATOR_NAME, ',', '') END AS BIZAGI_CASE_INITIATOR_NAME,
		CA.DATE_ID AS BIZAGI_CASE_CREATION_DATE,
		ZEROIFNULL(D.BIZAGI_DEPARTMENT_ID) AS BIZAGI_DEPARTMENT_ID,
		ZEROIFNULL(P.BIZAGI_PURCHASE_TYPE_ID) AS BIZAGI_PURCHASE_TYPE_ID,
		S.BIZAGI_IO,
		ZEROIFNULL(O.PNL_COST_CENTER_ID) AS PNL_COST_CENTER_ID,
		S.BIZAGI_PLANNED_DELIVERY_DATETIME,
		S.BIZAGI_AMOUNT_WOVAT,
		ZEROIFNULL(C.CURRENCY_ID) AS CURRENCY_ID,
		S.BIZAGI_AMOUNT_INIT_LCY,
		S.BIZAGI_AMOUNT_TEND_LCY,
		S.BIZAGI_VENDOR_CUSTOM,
		S.BIZAGI_VENDOR_NAME_LOCAL,
		S.BIZAGI_APPROVED_VENDOR_CUSTOM,
		S.BIZAGI_VENDOR1_NAME_LOCAL,
		ZEROIFNULL(T.BIZAGI_CONTRACT_TYPE_ID) AS BIZAGI_CONTRACT_TYPE_ID,
		ZEROIFNULL(S.BIZAGI_COMPANY_INVITED) AS BIZAGI_COMPANY_INVITED,
		ZEROIFNULL(S.BIZAGI_RECEIVED_OFFER) AS BIZAGI_RECEIVED_OFFER,
		ZEROIFNULL(S.BIZAGI_FIRST_OFFER_AMOUNT_VAT) AS BIZAGI_FIRST_OFFER_AMOUNT_VAT,
		ZEROIFNULL(S.BIZAGI_AVERAGE_AMOUNT_VAT) AS BIZAGI_AVERAGE_AMOUNT_VAT,
		ZEROIFNULL(S.BIZAGI_TAX_REFERENCE_NO) AS BIZAGI_TAX_REFERENCE_NO,
		S.BIZAGI_CASE_DESCRIPTION,
		S.BIZAGI_END_CONTRACT_DATETIME,
		ZEROIFNULL(BIZAGI_AMOUNT_INIT_LCY - BIZAGI_AMOUNT_TEND_LCY) AS BIZAGI_SAVING_AMOUNT,
		CASE WHEN BIZAGI_AMOUNT_TEND_LCY IS NOT NULL AND BIZAGI_AMOUNT_INIT_LCY IS NOT NULL
		    THEN BIZAGI_AMOUNT_TEND_LCY/BIZAGI_AMOUNT_INIT_LCY ELSE 0 END AS BIZAGI_SAVING_PERCENT,
		ZEROIFNULL(BIZAGI_FIRST_OFFER_AMOUNT_VAT - BIZAGI_AMOUNT_TEND_LCY) AS BIZAGI_SAVING_VS_FIRST_OFFER,
		ZEROIFNULL(BIZAGI_AVERAGE_AMOUNT_VAT - BIZAGI_AMOUNT_TEND_LCY) AS BIZAGI_SAVING_VS_AVERAGE_AMOUNT,
		C.CURRENCY_CODE
	FROM STG_LU_BIZAGI_CASE S
    FULL JOIN LU_EMPLOYEE E ON (
        CASE WHEN S.BIZAGI_CASE_INITIATOR_ID IS NOT NULL
                THEN CONCAT('00', S.BIZAGI_CASE_INITIATOR_ID) = E.SAP_HR_NO
            ELSE CASE WHEN E.EMPLOYEE_LOGIN IS NOT NULL
                THEN LEFT(UPPER(S.BIZAGI_CASE_INITIATOR_LOGIN), 8) = LEFT(UPPER(E.EMPLOYEE_LOGIN), 8)
            END
        END
    )
	JOIN LU_CALENDAR CA ON CA.DATE_ID = CAST(S.BIZAGI_CASE_CREATION_DATE AS DATE)
	LEFT JOIN LU_BIZAGI_DEPARTMENT D					ON S.BIZAGI_DEPARTMENT_NAME_INT 			= D.BIZAGI_DEPARTMENT_NAME_INT
	LEFT JOIN LU_BIZAGI_PURCHASE_TYPE P 				ON S.BIZAGI_PURCHASE_TYPE_NAME_INT 			= P.BIZAGI_PURCHASE_TYPE_NAME_INT
	LEFT JOIN LU_PNL_COST_CENTER O 				ON S.PNL_COST_CENTER_CODE 					= O.PNL_COST_CENTER_CODE
	LEFT JOIN LU_CURRENCY C 					ON S.CURRENCY_CODE 							= C.CURRENCY_CODE
	LEFT JOIN LU_BIZAGI_CONTRACT_TYPE T ON S.BIZAGI_CONTRACT_TYPE_NAME_INT = T.BIZAGI_CONTRACT_TYPE_NAME_INT
) S ON D.BIZAGI_CASE_NO = S.BIZAGI_CASE_NO
WHEN MATCHED THEN UPDATE SET
	D.BIZAGI_CASE_INITIATOR_ID			= S.BIZAGI_CASE_INITIATOR_ID,
	D.BIZAGI_CASE_INITIATOR_LOGIN		= S.BIZAGI_CASE_INITIATOR_LOGIN,
	D.BIZAGI_CASE_INITIATOR_NAME		= S.BIZAGI_CASE_INITIATOR_NAME,
	D.BIZAGI_CASE_CREATION_DATE	 		= S.BIZAGI_CASE_CREATION_DATE,
	D.BIZAGI_DEPARTMENT_ID 				= S.BIZAGI_DEPARTMENT_ID,
	D.BIZAGI_PURCHASE_TYPE_ID 			= S.BIZAGI_PURCHASE_TYPE_ID,
	D.BIZAGI_IO 						= S.BIZAGI_IO,
	D.PNL_COST_CENTER_ID 				= S.PNL_COST_CENTER_ID,
	D.BIZAGI_PLANNED_DELIVERY_DATETIME 	= S.BIZAGI_PLANNED_DELIVERY_DATETIME,
	D.BIZAGI_AMOUNT_WOVAT 				= S.BIZAGI_AMOUNT_WOVAT,
	D.CURRENCY_ID 						= S.CURRENCY_ID,
	D.BIZAGI_AMOUNT_INIT_LCY 			= S.BIZAGI_AMOUNT_INIT_LCY,
	D.BIZAGI_AMOUNT_TEND_LCY 			= S.BIZAGI_AMOUNT_TEND_LCY,
	D.BIZAGI_VENDOR_CUSTOM 				= S.BIZAGI_VENDOR_CUSTOM,
	D.BIZAGI_VENDOR_NAME_LOCAL 			= S.BIZAGI_VENDOR_NAME_LOCAL,
	D.BIZAGI_APPROVED_VENDOR_CUSTOM 	= S.BIZAGI_APPROVED_VENDOR_CUSTOM,
	D.BIZAGI_VENDOR1_NAME_LOCAL 		= S.BIZAGI_VENDOR1_NAME_LOCAL,
	D.BIZAGI_CONTRACT_TYPE_ID = 	S.BIZAGI_CONTRACT_TYPE_ID,
	D.BIZAGI_COMPANY_INVITED =	S.BIZAGI_COMPANY_INVITED,
	D.BIZAGI_RECEIVED_OFFER = 	S.BIZAGI_RECEIVED_OFFER,
	D.BIZAGI_FIRST_OFFER_AMOUNT_VAT= 	S.BIZAGI_FIRST_OFFER_AMOUNT_VAT,
	D.BIZAGI_AVERAGE_AMOUNT_VAT= 	S.BIZAGI_AVERAGE_AMOUNT_VAT,
	D.BIZAGI_TAX_REFERENCE_NO = 	S.BIZAGI_TAX_REFERENCE_NO,
	D.BIZAGI_CASE_DESCRIPTION = 	S.BIZAGI_CASE_DESCRIPTION,
	D.BIZAGI_END_CONTRACT_DATETIME = 	S.BIZAGI_END_CONTRACT_DATETIME,
	D.BIZAGI_SAVING_AMOUNT = S.BIZAGI_SAVING_AMOUNT,
	D.BIZAGI_SAVING_PERCENT = S.BIZAGI_SAVING_PERCENT,
	D.BIZAGI_SAVING_VS_FIRST_OFFER = S.BIZAGI_SAVING_VS_FIRST_OFFER,
	D.BIZAGI_SAVING_VS_AVERAGE_AMOUNT = S.BIZAGI_SAVING_VS_AVERAGE_AMOUNT,
	D.CURRENCY_CODE = S.CURRENCY_CODE
WHEN NOT MATCHED THEN INSERT (
	BIZAGI_CASE_NO,
	BIZAGI_CASE_INITIATOR_ID,
	BIZAGI_CASE_INITIATOR_LOGIN,
    BIZAGI_CASE_INITIATOR_NAME,
	BIZAGI_CASE_CREATION_DATE,
	BIZAGI_DEPARTMENT_ID,
	BIZAGI_PURCHASE_TYPE_ID,
	BIZAGI_IO,
	PNL_COST_CENTER_ID,
	BIZAGI_PLANNED_DELIVERY_DATETIME,
	BIZAGI_AMOUNT_WOVAT,
	CURRENCY_ID,
	BIZAGI_AMOUNT_INIT_LCY,
	BIZAGI_AMOUNT_TEND_LCY,
	BIZAGI_VENDOR_CUSTOM,
	BIZAGI_VENDOR_NAME_LOCAL,
	BIZAGI_APPROVED_VENDOR_CUSTOM,
	BIZAGI_VENDOR1_NAME_LOCAL,
	BIZAGI_CONTRACT_TYPE_ID,
	BIZAGI_COMPANY_INVITED,
	BIZAGI_RECEIVED_OFFER,
	BIZAGI_FIRST_OFFER_AMOUNT_VAT,
	BIZAGI_AVERAGE_AMOUNT_VAT,
	BIZAGI_TAX_REFERENCE_NO,
	BIZAGI_CASE_DESCRIPTION,
	BIZAGI_END_CONTRACT_DATETIME,
	BIZAGI_SAVING_AMOUNT,
	BIZAGI_SAVING_PERCENT,
	BIZAGI_SAVING_VS_FIRST_OFFER,
	BIZAGI_SAVING_VS_AVERAGE_AMOUNT,
	CURRENCY_CODE
) VALUES (
	S.BIZAGI_CASE_NO,
	S.BIZAGI_CASE_INITIATOR_ID,
	S.BIZAGI_CASE_INITIATOR_LOGIN,
    S.BIZAGI_CASE_INITIATOR_NAME,
	S.BIZAGI_CASE_CREATION_DATE,
	S.BIZAGI_DEPARTMENT_ID,
	S.BIZAGI_PURCHASE_TYPE_ID,
	S.BIZAGI_IO,
	S.PNL_COST_CENTER_ID,
	S.BIZAGI_PLANNED_DELIVERY_DATETIME,
	S.BIZAGI_AMOUNT_WOVAT,
	S.CURRENCY_ID,
	S.BIZAGI_AMOUNT_INIT_LCY,
	S.BIZAGI_AMOUNT_TEND_LCY,
	S.BIZAGI_VENDOR_CUSTOM,
	S.BIZAGI_VENDOR_NAME_LOCAL,
	S.BIZAGI_APPROVED_VENDOR_CUSTOM,
	S.BIZAGI_VENDOR1_NAME_LOCAL,
	S.BIZAGI_CONTRACT_TYPE_ID,
	S.BIZAGI_COMPANY_INVITED,
	S.BIZAGI_RECEIVED_OFFER,
	S.BIZAGI_FIRST_OFFER_AMOUNT_VAT,
	S.BIZAGI_AVERAGE_AMOUNT_VAT,
	S.BIZAGI_TAX_REFERENCE_NO,
	S.BIZAGI_CASE_DESCRIPTION,
	S.BIZAGI_END_CONTRACT_DATETIME,
	S.BIZAGI_SAVING_AMOUNT,
	S.BIZAGI_SAVING_PERCENT,
	S.BIZAGI_SAVING_VS_FIRST_OFFER,
	S.BIZAGI_SAVING_VS_AVERAGE_AMOUNT,
	S.CURRENCY_CODE
)
;

--F_BIZAGI_CASE
MERGE INTO LU_BIZAGI_TASK_STATUS D
USING (
	SELECT DISTINCT
		BIZAGI_TASK_STATUS_NAME_INT
	FROM STG_F_BIZAGI_CASE
) S ON D.BIZAGI_TASK_STATUS_NAME_INT = S.BIZAGI_TASK_STATUS_NAME_INT
WHEN NOT MATCHED THEN INSERT (BIZAGI_TASK_STATUS_NAME_INT) VALUES (S.BIZAGI_TASK_STATUS_NAME_INT)
;

MERGE INTO LU_BIZAGI_STATE D
USING (
	SELECT DISTINCT
		BIZAGI_STATE_NAME_INT
	FROM STG_F_BIZAGI_CASE
) S ON D.BIZAGI_STATE_NAME_INT = S.BIZAGI_STATE_NAME_INT
WHEN NOT MATCHED THEN INSERT (BIZAGI_STATE_NAME_INT) VALUES (S.BIZAGI_STATE_NAME_INT)
;

TRUNCATE TABLE F_BIZAGI_CASE_PURCHASE_CONTRACT
;

INSERT INTO F_BIZAGI_CASE_PURCHASE_CONTRACT (
    BIZAGI_APPROVEMENT_ID,
    BIZAGI_CASE_ID,
    BIZAGI_DEPARTMENT_ID,
    BIZAGI_SLT,
    COUNTRY_ID,
    BIZAGI_EMPLOYEE_ID,
    BIZAGI_EMPLOYEE_LOGIN,
    BIZAGI_EMPLOYEE_NAME,
    BIZAGI_STATE_ID,
    BIZAGI_TASK_STATUS_ID,
    BIZAGI_CASE_APPROVEMENT_DATETIME,
    BIZAGI_WI_ENTRY_DATETIME,
    BIZAGI_WI_SOLUTION_DATETIME,
    BIZAGI_WI_ESTIMATED_SOLUTION_DATETIME,
    BIZAGI_CASE_DURATION,
    BIZAGI_SLA_MINUTES,
    BIZAGI_RESOLUTION,
    BIZAGI_OBSERVATION
)
WITH SLT AS (
    SELECT DISTINCT
        S.BIZAGI_CASE_NO,
        D.BIZAGI_DEPARTMENT_ID,
        E.EMPLOYEE_NAME_INT AS BIZAGI_SLT
    FROM LU_BIZAGI_CASE S
    JOIN LU_BIZAGI_DEPARTMENT D    ON S.BIZAGI_DEPARTMENT_ID = D.BIZAGI_DEPARTMENT_ID
    JOIN LU_EMPLOYEE E ON CONCAT('00', D.SLT_SAP_HR_NO) = E.SAP_HR_NO
)
SELECT DISTINCT
    BIZAGI_APPROVEMENT_ID,
    BIZAGI_CASE_ID,
    BIZAGI_DEPARTMENT_ID,
    BIZAGI_SLT,
    COUNTRY_ID,
    BIZAGI_EMPLOYEE_ID,
    BIZAGI_EMPLOYEE_LOGIN,
    BIZAGI_EMPLOYEE_NAME,
    BIZAGI_STATE_ID,
    BIZAGI_TASK_STATUS_ID,
    BIZAGI_CASE_DATE,
    BIZAGI_WI_ENTRY_DATETIME,
    BIZAGI_WI_SOLUTION_DATETIME,
    BIZAGI_WI_ESTIMATED_SOLUTION_DATETIME,
    BIZAGI_CASE_DURATION,
    BIZAGI_SLA_MINUTES,
    BIZAGI_RESOLUTION,
    BIZAGI_OBSERVATION
FROM (
    SELECT
        S.BIZAGI_APPROVEMENT_ID,
        C.BIZAGI_CASE_ID,
        SLT.BIZAGI_DEPARTMENT_ID,
        SLT.BIZAGI_SLT,
        LC.COUNTRY_ID,
        ZEROIFNULL(E.EMPLOYEE_ID)                       AS BIZAGI_EMPLOYEE_ID,
        UPPER(SUBSTRING(S.BIZAGI_EMPLOYEE_LOGIN, 1, 8)) AS BIZAGI_EMPLOYEE_LOGIN,
        CASE WHEN E.EMPLOYEE_NAME_INT IS NOT NULL THEN E.EMPLOYEE_NAME_INT ELSE REPLACE(S.BIZAGI_EMPLOYEE_NAME, ',', '') END AS BIZAGI_EMPLOYEE_NAME,
        ST.BIZAGI_STATE_ID,
        T.BIZAGI_TASK_STATUS_ID,
        S.BIZAGI_CASE_DATE,
        SF.BIZAGI_WI_ENTRY_DATETIME,
        SF.BIZAGI_WI_SOLUTION_DATETIME,
        SF.BIZAGI_WI_ESTIMATED_SOLUTION_DATETIME,
        SF.BIZAGI_CASE_DURATION,
        SF.BIZAGI_SLA_MINUTES,
        S.BIZAGI_RESOLUTION,
        S.BIZAGI_OBSERVATION,
        RANK() OVER (PARTITION BY S.BIZAGI_APPROVEMENT_ID ORDER BY SF.BIZAGI_SLA_MINUTES DESC) AS RANK
    FROM LU_BIZAGI_CASE C
    RIGHT JOIN STG_F_BIZAGI_CASE_PURCHASE_CONTRACT S ON S.BIZAGI_CASE_NO = C.BIZAGI_CASE_NO
    JOIN SLT ON SLT.BIZAGI_CASE_NO = S.BIZAGI_CASE_NO
    JOIN LU_COUNTRY LC ON UPPER(S.BIZAGI_COUNTRY_NAME_INT) = LC.COUNTRY_NAME_INT
    RIGHT JOIN STG_F_BIZAGI_CASE SF ON C.BIZAGI_CASE_NO = SF.BIZAGI_CASE_NO
       AND (LEFT(TO_TIMESTAMP(SF.BIZAGI_WI_SOLUTION_DATETIME), 19) = LEFT(TO_TIMESTAMP(S.BIZAGI_CASE_DATE), 19)
       OR LEFT(TO_TIMESTAMP(SF.BIZAGI_WI_SOLUTION_DATETIME) + INTERVAL '1' SECOND, 19) = LEFT(TO_TIMESTAMP(S.BIZAGI_CASE_DATE), 19)
       OR LEFT(TO_TIMESTAMP(SF.BIZAGI_WI_SOLUTION_DATETIME) - INTERVAL '1' SECOND , 19) = LEFT(TO_TIMESTAMP(S.BIZAGI_CASE_DATE), 19))
    JOIN LU_BIZAGI_TASK_STATUS T ON S.BIZAGI_TASK_NAME = T.BIZAGI_TASK_STATUS_NAME_INT
    FULL JOIN LU_EMPLOYEE E ON (
        CASE WHEN S.BIZAGI_EMPLOYEE_ID IS NOT NULL
                THEN CONCAT('00', S.BIZAGI_EMPLOYEE_ID) = E.SAP_HR_NO
            ELSE CASE WHEN E.EMPLOYEE_LOGIN IS NOT NULL
                THEN LEFT(UPPER(S.BIZAGI_EMPLOYEE_LOGIN), 8) = LEFT(UPPER(E.EMPLOYEE_LOGIN), 8)
            END
        END
    )
    JOIN LU_BIZAGI_STATE ST ON SF.BIZAGI_STATE_NAME_INT = ST.BIZAGI_STATE_NAME_INT
)
WHERE RANK = 1
;

MERGE INTO F_BIZAGI_CASE_PURCHASE_CONTRACT DST
USING (
    SELECT
        BIZAGI_CASE_ID,
           BIZAGI_WI_SOLUTION_DATETIME,
        BIZAGI_WI_ENTRY_DATETIME,
               SUM(CAST(IS_HOLIDAY_RU as int)) + 2 as ABS_DAYS,
        BIZAGI_WI_ENTRY_DATETIME + LOCAL.ABS_DAYS AS BIZAGI_ACTIVE_ESTIMATED_SOLUTION_DATETIME,
       CASE WHEN BIZAGI_WI_SOLUTION_DATETIME - BIZAGI_WI_ENTRY_DATETIME >
            TO_DSINTERVAL(concat(to_char(2+SUM(CAST(IS_HOLIDAY_RU as int))), ' 00:00:00.000'))
            THEN 1 ELSE 0 END AS IS_OVERDUE_PATH
    FROM F_BIZAGI_CASE_PURCHASE_CONTRACT bcp
    join lu_calendar clsol on clsol.DATE_ID
        between to_date(bcp.BIZAGI_WI_ENTRY_DATETIME) and to_date(bcp.BIZAGI_WI_SOLUTION_DATETIME)
    GROUP BY BIZAGI_CASE_ID, bcp.BIZAGI_WI_SOLUTION_DATETIME, bcp.BIZAGI_WI_ENTRY_DATETIME
) SRC ON
    DST.BIZAGI_CASE_ID = SRC.BIZAGI_CASE_ID and
    dst.BIZAGI_WI_SOLUTION_DATETIME = src.BIZAGI_WI_SOLUTION_DATETIME
WHEN MATCHED THEN UPDATE SET
    DST.IS_OVERDUE_PATH = SRC.IS_OVERDUE_PATH,
    DST.BIZAGI_ACTIVE_ESTIMATED_SOLUTION_DATETIME = SRC.BIZAGI_ACTIVE_ESTIMATED_SOLUTION_DATETIME
;
