CREATE OR REPLACE VIEW MSTR_F_BIZAGI AS
WITH CTE AS (
    SELECT DISTINCT
        BIZAGI_CASE_ID,
        BIZAGI_DEPARTMENT_ID,
        BIZAGI_SLT,
        CASE BIZAGI_TASK_STATUS_ID
            WHEN 528
                THEN 1598
            WHEN 529
                THEN 1598
            WHEN 534
                THEN 427
            WHEN 538
                THEN 427
            WHEN 549
                THEN 73
            WHEN 551
                THEN 73
            WHEN 559
                THEN 73
            ELSE BIZAGI_TASK_STATUS_ID
            END AS BIZAGI_TASK_STATUS_ID,
        BIZAGI_EMPLOYEE_ID,
        BIZAGI_EMPLOYEE_NAME,
        BIZAGI_WI_ENTRY_DATETIME AS BIZAGI_WI_ENTRY_DATETIME_PATH,
        BIZAGI_WI_SOLUTION_DATETIME AS BIZAGI_WI_SOLUTION_DATETIME_PATH,
        IS_OVERDUE_PATH,
        COUNTRY_ID
    FROM F_BIZAGI_CASE_PURCHASE_CONTRACT
)
SELECT DISTINCT
    PC.BIZAGI_CASE_ID,
    CASE WHEN E.EMPLOYEE_ID != 0 THEN E.EMPLOYEE_NAME_INT ELSE REPLACE(BC.BIZAGI_CASE_INITIATOR_NAME, ',', '') END AS BIZAGI_CASE_INITIATOR_NAME,
    BC.BIZAGI_CONTRACT_TYPE_ID,
    CTE.BIZAGI_DEPARTMENT_ID,
    CTE.BIZAGI_SLT,
    CTE.BIZAGI_TASK_STATUS_ID,
    CTE.BIZAGI_EMPLOYEE_ID,
    CTE.BIZAGI_EMPLOYEE_NAME,
    CTE.IS_OVERDUE_PATH,
    CTE.COUNTRY_ID,
    CTE.BIZAGI_WI_ENTRY_DATETIME_PATH,
    CTE.BIZAGI_WI_SOLUTION_DATETIME_PATH,
    EXTRACT(DAY FROM CTE.BIZAGI_WI_SOLUTION_DATETIME_PATH - CTE.BIZAGI_WI_ENTRY_DATETIME_PATH) AS BIZAGI_DATE_DIFFERENCE_DAY,
    EXTRACT(HOUR FROM CTE.BIZAGI_WI_SOLUTION_DATETIME_PATH - CTE.BIZAGI_WI_ENTRY_DATETIME_PATH) AS BIZAGI_DATE_DIFFERENCE_HOUR,
    MIN(PC.BIZAGI_WI_ENTRY_DATETIME) AS BIZAGI_WI_ENTRY_DATETIME,
    MAX(PC.BIZAGI_WI_SOLUTION_DATETIME) AS BIZAGI_WI_SOLUTION_DATETIME,
    CASE WHEN CL.BIZAGI_CASE_NO IS NULL THEN 1 ELSE 0 END AS IS_ACTIVE,
        CASE WHEN LOCAL.IS_ACTIVE = 1
            THEN CASE WHEN MAX(PC.BIZAGI_ACTIVE_ESTIMATED_SOLUTION_DATETIME) > CURRENT_TIMESTAMP
                THEN 0
                ELSE 1 END
            ELSE CASE WHEN MAX(PC.BIZAGI_WI_SOLUTION_DATETIME) > MAX(PC.BIZAGI_WI_ESTIMATED_SOLUTION_DATETIME)
                THEN 1
                ELSE 0 END
        END IS_OVERDUE
FROM F_BIZAGI_CASE_PURCHASE_CONTRACT PC
JOIN CTE ON PC.BIZAGI_CASE_ID = CTE.BIZAGI_CASE_ID
JOIN LU_BIZAGI_CASE BC ON PC.BIZAGI_CASE_ID = BC.BIZAGI_CASE_ID
LEFT JOIN LU_EMPLOYEE E ON E.EMPLOYEE_ID = BC.BIZAGI_CASE_INITIATOR_ID
LEFT JOIN TMP_BIZAGI_CLOSED_CASE CL ON BC.BIZAGI_CASE_NO = CL.BIZAGI_CASE_NO
WHERE CTE.BIZAGI_TASK_STATUS_ID NOT IN (106, 526, 532, 537, 568) AND PC.BIZAGI_CASE_ID NOT IN (18612, 18608)
GROUP BY
    PC.BIZAGI_CASE_ID,
    LOCAL.BIZAGI_CASE_INITIATOR_NAME,
    BC.BIZAGI_CONTRACT_TYPE_ID,
    CTE.BIZAGI_DEPARTMENT_ID,
    CTE.BIZAGI_SLT,
    CTE.BIZAGI_TASK_STATUS_ID,
    CTE.BIZAGI_EMPLOYEE_ID,
    CTE.BIZAGI_EMPLOYEE_NAME,
    CTE.IS_OVERDUE_PATH,
    CTE.COUNTRY_ID,
    CTE.BIZAGI_WI_ENTRY_DATETIME_PATH,
    CTE.BIZAGI_WI_SOLUTION_DATETIME_PATH,
    LOCAL.BIZAGI_DATE_DIFFERENCE_DAY,
    LOCAL.BIZAGI_DATE_DIFFERENCE_HOUR,
    LOCAL.IS_ACTIVE
;