MERGE INTO HST_ECOM_RUSSIAN_POST DST
USING (
    SELECT *
    FROM (
    	IMPORT INTO (
            ORDER_NO VARCHAR(100),
            SHIPMENT_NO VARCHAR(100),
    	    STATUS_CODE VARCHAR(100),
    	    STATUS_DATE VARCHAR(100)
    	)
    	FROM CSV
    	AT '&1'
    	USER '&2'
    	IDENTIFIED BY '&3'
    	FILE '~/etl_data/ecom_russian_post/shipment_out.csv'
        COLUMN SEPARATOR = ';'
		ROW SEPARATOR = 'CRLF'
		COLUMN DELIMITER = ''
		TRIM
    	SKIP = 1
    )
) SRC ON
    SRC.ORDER_NO = DST.ORDER_NO AND
    SRC.SHIPMENT_NO = DST.SHIPMENT_NO
WHEN MATCHED THEN UPDATE SET
    DST.STATUS_CODE = SRC.STATUS_CODE,
    DST.STATUS_DATE = SRC.STATUS_DATE
WHEN NOT MATCHED THEN INSERT (
    ORDER_NO,
	SHIPMENT_NO,
    STATUS_CODE,
    STATUS_DATE
) VALUES (
    SRC.ORDER_NO,
	SRC.SHIPMENT_NO,
    SRC.STATUS_CODE,
    SRC.STATUS_DATE
);
