MERGE INTO LU_ECOM_SHIPMENT D
USING (
	SELECT DISTINCT
		SHIPMENT_NO
	FROM HST_ECOM_RUSSIAN_POST
	WHERE SHIPMENT_NO IS NOT NULL
) S
ON D.ECOM_SHIPMENT_NO = S.SHIPMENT_NO
WHEN NOT MATCHED THEN INSERT (
    ECOM_SHIPMENT_NO
)
VALUES (
    S.SHIPMENT_NO
)
;

MERGE INTO F_ECOM_COURIER DST
USING (
    SELECT
        RP.ECOM_ORDER_ID,
		RP.ECOM_SHIPMENT_ID,
		RP.ECOM_COURIER_STATUS_ID,
		RP.ECOM_COURIER_STATUS_DATETIME,
		RP.ECOM_SHIPMENT_NO,
		RP.ECOM_COURIER_SYSTEM_STATUS_DESCRIPTION,
	    RP.ECOM_COURIER_SYSTEM_STATUS_CODE
    FROM (
        SELECT
            L.ECOM_ORDER_ID,
            ZEROIFNULL(N.ECOM_SHIPMENT_ID) AS ECOM_SHIPMENT_ID,
            S.ECOM_COURIER_STATUS_ID,
            H.STATUS_DATE AS ECOM_COURIER_STATUS_DATETIME,
            N.ECOM_SHIPMENT_NO AS ECOM_SHIPMENT_NO,
            S.ECOM_COURIER_SYSTEM_STATUS_NAME AS ECOM_COURIER_SYSTEM_STATUS_DESCRIPTION,
            S.ECOM_COURIER_SYSTEM_STATUS_CODE AS ECOM_COURIER_SYSTEM_STATUS_CODE
        FROM HST_ECOM_RUSSIAN_POST H
        JOIN LU_ECOM_ORDER L ON L.ECOM_ORDER_NO = LEFT(H.ORDER_NO, LENGTH(H.ORDER_NO) - 3)
        LEFT JOIN LU_ECOM_SHIPMENT N ON N.ECOM_SHIPMENT_NO = H.SHIPMENT_NO
        JOIN REL_ECOM_COURIER_STATUS S ON S.ECOM_COURIER_SYSTEM_STATUS_CODE = H.STATUS_CODE
        JOIN LU_ECOM_SHIPPING_AGENT LSA ON S.ECOM_SHIPPING_AGENT_ID = LSA.ECOM_SHIPPING_AGENT_ID
        WHERE LSA.ECOM_SHIPPING_AGENT_CODE = '3680000022'
    ) RP
) SRC ON
    SRC.ECOM_ORDER_ID = DST.ECOM_ORDER_ID AND
    SRC.ECOM_SHIPMENT_ID = DST.ECOM_SHIPMENT_ID AND
    SRC.ECOM_COURIER_STATUS_ID = DST.ECOM_COURIER_STATUS_ID
WHEN MATCHED THEN UPDATE SET
    DST.ECOM_COURIER_STATUS_DATETIME = SRC.ECOM_COURIER_STATUS_DATETIME,
    DST.ECOM_SHIPMENT_NO = SRC.ECOM_SHIPMENT_NO,
    DST.ECOM_COURIER_SYSTEM_STATUS_DESCRIPTION = SRC.ECOM_COURIER_SYSTEM_STATUS_DESCRIPTION,
    DST.ECOM_COURIER_SYSTEM_STATUS_CODE = SRC.ECOM_COURIER_SYSTEM_STATUS_CODE
WHEN NOT MATCHED THEN INSERT (
    ECOM_ORDER_ID,
    ECOM_SHIPMENT_ID,
    ECOM_COURIER_STATUS_ID,
    ECOM_COURIER_STATUS_DATETIME,
    ECOM_SHIPMENT_NO,
    ECOM_COURIER_SYSTEM_STATUS_DESCRIPTION,
    ECOM_COURIER_SYSTEM_STATUS_CODE
)
VALUES (
    SRC.ECOM_ORDER_ID,
    SRC.ECOM_SHIPMENT_ID,
    SRC.ECOM_COURIER_STATUS_ID,
    SRC.ECOM_COURIER_STATUS_DATETIME,
    SRC.ECOM_SHIPMENT_NO,
	SRC.ECOM_COURIER_SYSTEM_STATUS_DESCRIPTION,
	SRC.ECOM_COURIER_SYSTEM_STATUS_CODE
)
;
