TRUNCATE TABLE STG_NATIONAL_CATALOG;

INSERT INTO STG_NATIONAL_CATALOG
SELECT
	GTIN,
    GOOD_NAME,
    TNVED,
    GOOD_STATUS,
    cast(UPDATED_DATE AS DATE) AS UPDATED_DATE
FROM (
	IMPORT INTO (
		GTIN         VARCHAR(50) UTF8,
        GOOD_NAME    VARCHAR(200) UTF8,
        TNVED        VARCHAR(50) UTF8,
        GOOD_STATUS  VARCHAR(32) UTF8,
        UPDATED_DATE VARCHAR(50) UTF8
	)
	FROM CSV
    AT '&1'
    USER '&2'
    IDENTIFIED BY '&3'
    FILE '~/etl_data/national_catalog/national_catalog.csv'
    COLUMN SEPARATOR = ';'
    ROW SEPARATOR = 'CRLF'
    TRIM
)
;
