MERGE INTO LU_EAN DST
USING (
    SELECT
        LU.EAN_ID AS EAN_ID,
        STG.GTIN AS EAN_NO
    FROM STG_NATIONAL_CATALOG STG
    LEFT JOIN LU_EAN LU
        ON STG.GTIN = LU.EAN_NO
) SRC ON
    DST.EAN_ID = SRC.EAN_ID
WHEN NOT MATCHED THEN INSERT (
    EAN_NO
)
VALUES (
    SRC.EAN_NO
)
;

MERGE INTO LU_TNVED DST
USING (
    SELECT
        LU.TNVED_ID AS TNVED_ID,
        STG.TNVED AS TNVED_NO
    FROM STG_NATIONAL_CATALOG STG
    LEFT JOIN LU_TNVED LU
        ON STG.TNVED = LU.TNVED_NO
) SRC ON
    DST.TNVED_ID = SRC.TNVED_ID
WHEN NOT MATCHED THEN INSERT (
    TNVED_NO
)
VALUES (
    SRC.TNVED_NO
)
;
